-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
DROP TYPE IF EXISTS user_role CASCADE;
CREATE TYPE user_role AS ENUM ('admin', 'client', 'seller');
CREATE TABLE IF NOT EXISTS public.users (
    id bigserial NOT NULL,
    name character varying(25) NOT NULL,
    email text NOT NULL,
    password character varying(25) NOT NULL,
    role user_role NOT NULL DEFAULT 'client',
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.products (
    id bigserial NOT NULL,
    name character varying(25) NOT NULL,
    description text NOT NULL,
    price numeric(10, 2) NOT NULL,
    image_url text NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.reviews (
    id bigserial NOT NULL,
    user_id integer NOT NULL,
    product_id integer NOT NULL,
    description text NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.orders (
    id bigserial NOT NULL,
    user_id integer NOT NULL,
    product_id integer NOT NULL,
    date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS public.products
ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE IF EXISTS public.reviews
ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE IF EXISTS public.reviews
ADD CONSTRAINT product_id FOREIGN KEY (product_id) REFERENCES public.products (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE IF EXISTS public.orders
ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE IF EXISTS public.orders
ADD CONSTRAINT product_id FOREIGN KEY (product_id) REFERENCES public.products (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
END;